blueprint:
  name: Molette Ikea Bilresa
  description: |
    Blueprint pour la télécommande Ikea Bilresa Matter (bouton + molette pour 3 canaux différents)
    Version : 2026-02-07
    Infos : https://community.home-assistant.io/t/ikea-bilresa-scroll-wheel-blueprint-matter/965365
  domain: automation

  # input selectors
  input:
    remote:
      name: Télécommande
      description: "Télécommande Ikea Bilresa avec molette de défilement"
      selector:
        device:
          filter:
            manufacturer: IKEA of Sweden
            model: BILRESA scroll wheel

    # input selectors: channel 1
    channel1_section:
      name: Canal 1
      collapsed: true
      input:
        click_action_ch1:
          name: "Canal 1 : action <clic>"
          default: []
          selector:
            action: {}

        double_click_action_ch1:
          name: "Canal 1 : action <double clic>"
          default: []
          selector:
            action: {}

        triple_click_action_ch1:
          name: "Canal 1 : action <triple clic>"
          default: []
          selector:
            action: {}

        long_click_action_ch1:
          name: "Canal 1 : action <appui long>"
          description: ""
          default: []
          selector:
            action: {}

        on_hold_action_ch1:
          name: "Canal 1 : action <maintien>"
          description: "Répète l’action tant que le bouton est maintenu (voir aussi on_hold_delay)"
          default: []
          selector:
            action: {}

        scroll_wheel_target_ch1:
          name: "Canal 1 : entité contrôlée par la molette"
          description: |
            Lumière ou lecteur média contrôlé par la molette pour le canal 1
            - laisser vide pour le mode molette <personnalisé>
          selector:
            entity:
              multiple: true
              filter:
                domain:
                  - light
                  - media_player
          default: []

        scroll_wheel_mode_ch1:
          selector:
            select:
              options:
                - "lights: dim"
                - "lights: color temp and color hue"
                - "lights: color temp only"
                - "lights: color hue only"
                - "media: volume control"
                - "dynamic: choose from input_select"
                - "user defined"
          default: "lights: dim"
          name: "Canal 1 : mode de la molette"
          description: "Choisir l’attribut de l’entité cible contrôlé par la molette"

        scroll_wheel_mode_dynamic_ch1:
          selector:
            entity:
              filter:
                domain:
                  - input_select
          default:
          name: "Canal 1 : input_select pour mode dynamique"
          description: |-
            Utilisé uniquement pour le mode molette <dynamic>.
            Créer un input_select contenant les modes possibles, par exemple :
            - lights: dim
            - lights: color temp only

        scroll_wheel_mode_ext_ch1:
          selector:
            select:
              options:
                - "relaxed"
                - "instant"
          default: "relaxed"
          name: "Canal 1 : mode d’évaluation de la molette"
          description: |
            <relaxed> : une action après le défilement
            <instant> : plusieurs actions pendant le défilement

            Attention :
            pour le mode <instant> il faut activer les 9 capteurs cachés du Bilresa

        scroll_wheel_user_action_ch1:
          name: "Canal 1 : action molette personnalisée"
          description: |
            Utilisé uniquement pour le mode <user defined>

            Variables disponibles :
            - <scroll_clicks>
            - <scroll_direction> ('left' ou 'right')
          default: []
          selector:
            action: {}

    # input selectors: channel 2
    channel2_section:
      name: Canal 2
      collapsed: true
      input:
        click_action_ch2:
          name: "Canal 2 : action <clic>"
          default: []
          selector:
            action: {}

        double_click_action_ch2:
          name: "Canal 2 : action <double clic>"
          default: []
          selector:
            action: {}

        triple_click_action_ch2:
          name: "Canal 2 : action <triple clic>"
          default: []
          selector:
            action: {}

        long_click_action_ch2:
          name: "Canal 2 : action <appui long>"
          description: ""
          default: []
          selector:
            action: {}

        on_hold_action_ch2:
          name: "Canal 2 : action <maintien>"
          description: "Répète l’action tant que le bouton est maintenu (voir aussi on_hold_delay)"
          default: []
          selector:
            action: {}

        scroll_wheel_target_ch2:
          name: "Canal 2 : entité contrôlée par la molette"
          description: |
            Lumière ou lecteur média contrôlé par la molette pour le canal 2
            - laisser vide pour le mode molette <personnalisé>
          selector:
            entity:
              multiple: true
              filter:
                domain:
                  - light
                  - media_player
          default: []

        scroll_wheel_mode_ch2:
          selector:
            select:
              options:
                - "lights: dim"
                - "lights: color temp and color hue"
                - "lights: color temp only"
                - "lights: color hue only"
                - "media: volume control"
                - "dynamic: choose from input_select"
                - "user defined"
          default: "lights: dim"
          name: "Canal 2 : mode de la molette"
          description: "Choisir l’attribut de l’entité cible contrôlé par la molette"

    # input selectors: channel 3
    channel3_section:
      name: Canal 3
      collapsed: true
      input:
        click_action_ch3:
          name: "Canal 3 : action <clic>"
          default: []
          selector:
            action: {}

        double_click_action_ch3:
          name: "Canal 3 : action <double clic>"
          default: []
          selector:
            action: {}

        triple_click_action_ch3:
          name: "Canal 3 : action <triple clic>"
          default: []
          selector:
            action: {}

        long_click_action_ch3:
          name: "Canal 3 : action <appui long>"
          description: ""
          default: []
          selector:
            action: {}

        on_hold_action_ch3:
          name: "Canal 3 : action <maintien>"
          description: "Répète l’action tant que le bouton est maintenu (voir aussi on_hold_delay)"
          default: []
          selector:
            action: {}

    # global settings
    global_setting:
      name: Paramètres globaux
      collapsed: true
      input:

        dim_step_pct:
          name: Pas de variation luminosité (%)
          description: "variation de luminosité en %"
          default: 5
          selector:
            number:
              mode: box

        dim_min_pct:
          name: Luminosité minimale
          description: "luminosité minimale en %"
          default: 5
          selector:
            number:
              mode: box

        min_color_temp:
          name: Température couleur minimale
          description: "température minimale en Kelvin"
          default: 2200
          selector:
            number:
              mode: box

        max_color_temp:
          name: Température couleur maximale
          description: "température maximale en Kelvin"
          default: 4000
          selector:
            number:
              mode: box

        color_temp_step:
          name: Pas de température couleur
          description: "variation en Kelvin"
          default: 100
          selector:
            number:
              mode: box

        color_hue_step:
          name: Pas de teinte
          description: "variation en degrés (0-360)"
          default: 4
          selector:
            number:
              mode: box

        color_saturation:
          name: Saturation couleur
          description: "saturation en %"
          default: 100
          selector:
            number:
              mode: box

        volume_step_pct:
          name: Pas de variation volume
          description: "variation de volume en %"
          default: 3.5
          selector:
            number:
              mode: box

        volume_use_up_down_for_instant:
          name: Utiliser volume_up / volume_down en mode instant
          description: |
            En mode instant, utiliser les actions volume_up / volume_down
            plutôt que volume_step_pct
          default: true
          selector:
            boolean:

        volume_max_pct:
          name: Volume maximum
          description: "volume maximum en %"
          default: 70
          selector:
            number:
              mode: box

        on_hold_delay:
          name: Délai maintien
          description: délai entre deux actions lors d’un appui maintenu
          default: 0.1
          selector:
            number:
              mode: box
              step: 0.1

        max_queued_automation_calls:
          name: Nombre max d’actions en file
          description: |
            Augmenter si vous voulez accepter plus d’appels d’automatisation
          default: 10
          selector:
            number:
              mode: box
              step: 1